import Head from "next/head";
import { Inter } from "next/font/google";

import styles from "./page.module.css";
import { useEffect, useState } from "react";
import useSWR from "swr";
import { Input, UserInfo } from "./prompts";
import { Advice } from "./gpt";
import { WarningArea } from "../types";
import Map from "./components/Map";

const fetcher = (url: string) => fetch(url).then(res => res.json());

const initialUserInfo: UserInfo = {
  elderly: false,
  noVehicle: false,
  hasLivestock: false,
  hasFirefightingEquipment: false,
  requiresAssistance: false,
  mobilityIssues: false,
  visionImpaired: false,
  hearingImpaired: false,
  accessIssues: false,
};

export default function Home() {
  const [userInfo, setUserInfo] = useState<UserInfo>(initialUserInfo);
  const [sendingPrompt, setSendingPrompt] = useState(false);
  const { data } = useSWR<WarningArea[]>("/api/warnings", fetcher);
  const warningAreas = data || [];

  const onClick = (warningArea: WarningArea) => {
    console.log("On Click", { sendingPrompt });

    setSendingPrompt(true);

    postRequest(warningArea, userInfo)
      .then(advice => {
        console.log(advice);
        postNotification(advice);
      })
      .finally(() => setSendingPrompt(false));
  };

  return (
    <>
      <Head>
        <title>csyewwww</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Map onClick={onClick} warningAreas={warningAreas} />
      </main>
    </>
  );
}

async function postRequest(
  warningArea: WarningArea,
  userInfo: UserInfo
): Promise<Advice> {
  console.log("Inside warning area", { location, warningArea });

  const input: Input = {
    incident: {
      cadNumber: warningArea.cadNumber,
      polygonLevel: "",
      type: "Advice",
    },
    user: userInfo,
  };

  const response = await fetch("/api/advice", {
    method: "POST",
    body: JSON.stringify(input),
  });
  if (!response.ok) {
    throw new Error(response.status + " " + response.statusText);
  }
  return await response.json();
}

async function postNotification(advice: Advice): Promise<void> {
  if (Notification.permission != "granted") {
    const result = await Notification.requestPermission();
    if (result == "denied") {
      return;
    }
  }

  const n = new Notification(advice.Title, {
    body: advice.ShortDescription,
    icon: iconLink(advice.IncidentType),
  });
  n.addEventListener("click", () => console.log("Clicked!"));
  n.addEventListener("error", e => console.log("Error", e));
  n.addEventListener("show", e => console.log("Show", e));
}

function iconLink(text: string): string | undefined {
  switch (text.toLocaleLowerCase()) {
    case "fire":
      return "https://em-content.zobj.net/thumbs/240/google/350/fire_1f525.png";
    default:
      return undefined;
  }
}
