import Head from 'next/head'
import { Inter } from 'next/font/google'

import styles from './page.module.css'
import { useEffect, useState } from 'react'
import useSWR from "swr"
import { Input, UserInfo } from './prompts'
import { Advice } from './gpt'
import { WarningArea } from '../types'
import Map from "./components/Map";

const fetcher = (url: string) => fetch(url).then(res => res.json());

const initialUserInfo: UserInfo = {
  elderly: false,
  noVehicle: false,
  hasLivestock: false,
  hasFirefightingEquipment: false,
  requiresAssistance: false,
  mobilityIssues: false,
  visionImpaired: false,
  hearingImpaired: false,
  accessIssues: false,
};


export default function Home() {
  const [advice, setAdvice] = useState<Advice>();
  const [userInfo, setUserInfo] = useState<UserInfo>(initialUserInfo);
  const [sendingPrompt, setSendingPrompt] = useState(false);
  const { data } = useSWR<WarningArea[]>("/api/warnings", fetcher);
  const warningAreas = data || [];

  const onClick = (warningArea: WarningArea) => {
    console.log("On Click", { sendingPrompt });

    setSendingPrompt(true);

    postRequest(warningArea, userInfo)
      .then(advice => {
        console.log(advice);
        setAdvice(advice);
      })
      .finally(() => setSendingPrompt(false));
  };

  console.log(advice);

  return (
    <>
      <Head>
        <title>csyewwww</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Map onClick={onClick} warningAreas={warningAreas} />
      </main>
    </>
  );
}

async function postRequest(
  warningArea: WarningArea,
  userInfo: UserInfo
): Promise<Advice> {
  console.log("Inside warning area", { location, warningArea });

  const input: Input = {
    incident: {
      cadNumber: warningArea.cadNumber,
      polygonLevel: "",
      type: "Advice",
    },
    user: userInfo,
  };

  const response = await fetch("/api/advice", {
    method: "POST",
    body: JSON.stringify(input),
  });
  console.log(response.status);
  if (!response.ok) {
    throw new Error(response.status + " " + response.statusText);
  }
  const advice = await response.json();
  console.log("Result", advice);

  return advice;
}
